name: Auto Deploy AI Scraper

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH & Run deploy.sh
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          chmod +x /home/ec2-user/Ai-scraper/deploy.sh
          /home/ec2-user/Ai-scraper/deploy.sh
